SELECT
  K12INTEL_DW.DTBL_STUDENTS.STUDENT_ID,
   K12INTEL_DW.FTBL_ENROLLMENTS.Prod_begin_enroll_date,
   K12INTEL_DW.FTBL_ENROLLMENTS.prod_registration_date,
  Registration_School_Dates.date_value,
   Withdrawal_School_Dates.date_value,
  K12INTEL_DW.FTBL_ENROLLMENTS.Prod_end_enroll_date,
  K12INTEL_DW.FTBL_ENROLLMENTS.WITHDRAW_DATE

FROM
  K12INTEL_DW.FTBL_ENROLLMENTS,
  K12INTEL_DW.DTBL_STUDENTS,
  K12INTEL_DW.DTBL_SCHOOL_DATES  Registration_School_Dates,
  K12INTEL_DW.DTBL_SCHOOL_DATES  Withdrawal_School_Dates,
  K12INTEL_DW.DTBL_CALENDAR_DATES  Registration_Calendar_Dates,
  K12INTEL_DW.DTBL_CALENDAR_DATES  Withdrawal_Calendar_Dates,
  K12INTEL_DW.DTBL_SCHOOLS,
  K12INTEL_DW.DTBL_SCHOOLS_EXTENSION,
  K12INTEL_DW.XREF_DOMAIN_DECODES  START_CURRENT_GRADE_DECODE,
  K12INTEL_DW.XREF_DOMAIN_DECODES  END_CURRENT_GRADE_DECODE
WHERE
  ( Registration_School_Dates.SCHOOL_DATES_KEY=K12INTEL_DW.FTBL_ENROLLMENTS.SCHOOL_DATES_KEY_REGISTER  )
  AND  ( Registration_Calendar_Dates.CALENDAR_DATE_KEY=K12INTEL_DW.FTBL_ENROLLMENTS.CAL_DATE_KEY_REGISTER  )
    AND  ( K12INTEL_DW.FTBL_ENROLLMENTS.SCHOOL_KEY=K12INTEL_DW.DTBL_SCHOOLS.SCHOOL_KEY)
  AND  ( K12INTEL_DW.DTBL_STUDENTS.STUDENT_KEY=K12INTEL_DW.FTBL_ENROLLMENTS.STUDENT_KEY  )
  AND  ( K12INTEL_DW.FTBL_ENROLLMENTS.SCHOOL_DATES_KEY_END_ENROLL=Withdrawal_School_Dates.SCHOOL_DATES_KEY  )
  AND  ( K12INTEL_DW.FTBL_ENROLLMENTS.CAL_DATE_KEY_END_ENROLL=Withdrawal_Calendar_Dates.CALENDAR_DATE_KEY  )
 and  K12INTEL_DW.FTBL_ENROLLMENTS.prod_admit_school_year = '2012'
