SELECT
  st.student_key,
  st.STUDENT_ID,
  st.STUDENT_GENDER,
  st.STUDENT_RACE,
  e.ENTRY_GRADE_CODE,
  sch.school_code,
  sch.SCHOOL_NAME,
  ste.STUDENT_FOODSERVICE_INDICATOR,
  ste.STUDENT_SPECIAL_ED_INDICATOR,
  ste.STUDENT_ESL_INDICATOR,
  schx.GROUP2
FROM
  K12INTEL_DW.FTBL_ENROLLMENTS e
  INNER JOIN K12INTEL_DW.DTBL_STUDENTS_EVOLVED ste ON StE.STUDENT_EVOLVE_KEY=E.STUDENT_EVOLVE_KEY
  INNER JOIN K12INTEL_DW.DTBL_STUDENTS st ON ST.STUDENT_KEY=E.STUDENT_KEY
  INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES  Regdate ON Regdate.CALENDAR_DATE_KEY=e.CAL_DATE_KEY_REGISTER
  INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES  Wddate ON E.CAL_DATE_KEY_END_ENROLL=WDDATE.CALENDAR_DATE_KEY
  INNER JOIN K12INTEL_DW.DTBL_SCHOOLS sch ON E.SCHOOL_KEY=SCH.SCHOOL_KEY
  INNER JOIN K12INTEL_DW.DTBL_SCHOOLS_EXTENSION schx ON SCH.SCHOOL_KEY=schx.SCHOOL_KEY
WHERE
--   Regdate.DATE_VALUE  <=  '09-01-2013 00:00:00'
--   AND  wddate.DATE_VALUE  >=  '09-01-2013 00:00:00'
				Regdate.DATE_VALUE  >  to_Date (  '06-01-2015', 'mm/dd/yyyy' )
		AND wddate.DATE_VALUE  < to_date (  '08-30-2015', 'MM/DD/YYYY'  )
   	AND e.ENROLLMENT_TYPE  =  'Actual'
   	and sch.school_code in ('9090', '9052', '9032')

